/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const SuperAgentEnvironment = {
    Default: "https://api.beta.superagent.sh",
} as const;


//i fix this
//I fix this again

export type SuperAgentEnvironment = typeof SuperAgentEnvironment.Default;
